import dynamic from "next/dynamic";
import Head from "next/head";
import { useRouter } from "next/router";
import { ChangeEvent, useContext, useState } from "react";
import Button from "../components/Button";
import { Input } from "../components/input";
import { InputSelect } from "../components/InputSelect";
import DropDawCity from "../components/InputSelect/DropDawCity";
import DropDawStates from "../components/InputSelect/DropDrawStates";
import { SearchContext } from "../hooks/useSearchAddress";
//import { FormsContext } from "../hooks/UseFormProvider";
import * as S from "../styles/Pages/SearchAddress";
 type FindCepProps={   
     state:string  
 }
 
export default function FindCep() {
  const router = useRouter();
  const {register, handleOnChangeUser,handleKeyUp,inputController   }=useContext(SearchContext);
    const [formVlaues,setFormValues]=useState<FindCepProps>()
    
 function findAndressRouter() {
    router.push("/findAddress");
  }
   const handleInputChange=(e:ChangeEvent<HTMLSelectElement> )=>{
      e.preventDefault
    const {name,value}  =e.target
    setFormValues({...formVlaues,[name]:value})

  }
  const state=formVlaues?.state


const PDFViewer = dynamic(() => import("../components/Print/pdf-viewer"), {
  ssr: false
});

  return (
    <S.Container>
      <Head>
        <title>Inicio | Buscar Endereço </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="headerArea">
        <InputSelect label="Estados" htmlFor="state" {...register("state")} />
        <DropDawStates     onChange={handleInputChange}  />
        <InputSelect label="Cidades"  htmlFor="city" {...register("city")} />
        <DropDawCity state={state }  />
         <Input
         {...register("code")}
          htmlFor="zipcode"
          label="Bairro"
          placeholder="Jardim Fátima"
          name="district"
         
          onChange={handleOnChangeUser}
          value={inputController}
          onKeyUp={handleKeyUp}
          maxLength={9}
        />
    
      </header>

      <section className="groupButtons">
        <Button /*</section>onClick={findAndressRouter}*/>Voltar</Button>
        <Button>Pesquisar</Button>
        <PDFViewer/>
      </section>
    </S.Container>
  );
}

