import Head from "next/head";
import { useRouter } from "next/router";
import React, { useContext } from 'react';
import Button from "../components/Button";
import { Input } from "../components/input";
import { SearchContext } from "../hooks/useSearchAddress";
//import { FormsContext } from "../hooks/UseFormProvider";
import * as S from "../styles/Pages/SearchAddress";


export default function SearchAndress() {
  const router = useRouter();
  const {
   
    handleOnChangeUser,
    inputController,
   onClickZipCode,
   buttonController,
    handleKeyUp,
    message
  } = useContext(SearchContext);

  function homeRouter() {
    router.push("/");
  }
  
  return  (
    <S.Container>
      <Head>
        <title>Inicio | Buscar Endereço </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="headerArea">
        <Input
         // {...register("code")}
          htmlFor="zipcode"
          label="CEP*"
          placeholder="00000-000"
          name="zipcode"
          inputMode="numeric"
          onChange={handleOnChangeUser}
          value={inputController}
          onKeyUp={handleKeyUp}
          maxLength={9}
        />
         
      </header>
      
        <span>{message}</span>
      
      <section className="groupButtons">
        <Button  onClick={homeRouter} >Voltar</Button>
        <Button onClick={onClickZipCode} disabled={buttonController}>
          Buscar
        </Button>
      </section>
    </S.Container>
  );
}

 

