import Head from "next/head";
import { useRouter } from "next/router";
import { ChangeEvent, useContext, useState } from "react";
import Button from "../../components/Button";
import { Input } from "../../components/input";
import { InputSelect } from "../../components/InputSelect";
import DropDawCity from "../../components/InputSelect/DropDawCity";
import DropDawStates from "../../components/InputSelect/DropDrawStates";
import { SearchContext } from "../../hooks/useSearchAddress";
//import { FormsContext } from "../hooks/UseFormProvider";
import * as S from "../../styles/Pages/SearchAddress";
 type FindCepProps={   
     state:string  
 }
 
export default function FindCep({city}) {
  const router = useRouter();
  const {register,message,searchCepRequest,setSelectedAddress,selectedAddress   }=useContext(SearchContext);
    const [formVlaues,setFormValues]=useState<FindCepProps>()
  const [cities,setCities]=useState([])
  const [enabledCep,setEnabledCep]=useState(false)
    
 function findAndressRouter() {
    router.push("/findAddress");
  }
   const handleInputChange=(e:ChangeEvent<HTMLSelectElement> )=>{
      e.preventDefault
    const {name,value}  =e.target
    setFormValues({...formVlaues,[name]:value})
    
  }
  const state=formVlaues?.state


  return (
    <S.Container>
      <Head>
        <title>Inicio | Buscar CEP </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="headerArea">
        <InputSelect label="Estados" htmlFor="state"  />
        <DropDawStates     onChange={handleInputChange}  />
        <InputSelect label="Cidades"  htmlFor="city" />
        <DropDawCity state={state }  />
         <Input
         {...register("address")}
          htmlFor="address"
          label="Bairro"
          placeholder="Jardim Fátima"
          name="andrress"
         
          onChange={e=>setSelectedAddress(e.target.value)}
          value={selectedAddress}
          
         
        />

      </header>

      <section className="groupButtons">
        <Button /*</section>onClick={findAndressRouter}*/>Voltar</Button>
        <Button onClick={ searchCepRequest } >Pesquisar</Button>
       
      </section>
    </S.Container>
  );
}